const PAID_STATUS = "PAID"
const DECLINED_STATUS = "DECLINED"
const CANCELED_STATUS = "CANCELED"
const AUTHORIZED_STATUS = "AUTHORIZED"
const REFUNDED_STATUS = "REFUNDED"
const PENDING_STATUS = "PENDING"

const VISA_ACCEPT_SELECT_VALUE = "visa-ok"
const VISA_DECLINE_SELECT_VALUE = "visa-not-ok"
const MASTER_CARD_ACCEPT_SELECT_VALUE = "master-card-ok"
const MASTER_CARD_DECLINE_SELECT_VALUE = "master-card-not-ok"
const AMEX_ACCEPT_SELECT_VALUE = "amex-ok"
const AMEX_DECLINE_SELECT_VALUE = "amex-not-ok"
const ELO_ACCEPT_SELECT_VALUE = "elo-ok"
const ELO_DECLINE_SELECT_VALUE = "elo-not-ok"
const HYPER_ACCEPT_SELECT_VALUE = "hyper-ok"
const HYPER_DECLINE_SELECT_VALUE = "hyper-not-ok"

const PAID_RESULT = 0
const NOT_PAID_RESULT = 1
const ERROR_RESULT = 2

const MAX_MINUTES_FOR_PIX_QR_CODE_AVAILABILITY = 30
const MAX_TRIES_FOR_CHECKING = 100

const STATUS_ENDPOINT = "/pagamentos/status"

const PAYMENT_FALLBACK = "/paymentFallback"
const REFERENCE_ID_URL_PARAM = "ref"
const RESULT_URL_PARAM = "result"

module.exports = {
    PAID_STATUS,
    DECLINED_STATUS,
    CANCELED_STATUS,
    AUTHORIZED_STATUS,
    REFUNDED_STATUS,
    PAID_RESULT,
    NOT_PAID_RESULT,
    ERROR_RESULT,
    MAX_TRIES_FOR_CHECKING,
    STATUS_ENDPOINT,
    PAYMENT_FALLBACK,
    REFERENCE_ID_URL_PARAM,
    RESULT_URL_PARAM,
    VISA_ACCEPT_SELECT_VALUE,
    VISA_DECLINE_SELECT_VALUE,
    MASTER_CARD_ACCEPT_SELECT_VALUE,
    MASTER_CARD_DECLINE_SELECT_VALUE,
    AMEX_ACCEPT_SELECT_VALUE,
    AMEX_DECLINE_SELECT_VALUE,
    ELO_ACCEPT_SELECT_VALUE,
    ELO_DECLINE_SELECT_VALUE,
    HYPER_ACCEPT_SELECT_VALUE,
    HYPER_DECLINE_SELECT_VALUE,
}